import * as React from 'react'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/shared/lib/utils'
import { Slot } from 'radix-ui'

// Generated by shadcn (radix-vega), restyled to the canvas `.btn` rules in design/sino-ui/project/sino.css.
const buttonVariants = cva(
  "inline-flex shrink-0 cursor-pointer items-center justify-center gap-2 rounded-sm border border-transparent text-sm font-semibold tracking-[-0.005em] whitespace-nowrap select-none transition-[background-color,border-color,color,transform] duration-(--dur-hover) ease-out outline-none focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring focus-visible:outline-solid disabled:pointer-events-none disabled:opacity-38 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4.5",
  {
    variants: {
      variant: {
        primary: 'bg-primary text-primary-foreground hover:-translate-y-px hover:bg-primary-hover',
        secondary: 'border-border-strong bg-surface text-foreground hover:border-subtle-foreground hover:bg-hover',
        ghost: 'text-muted-foreground hover:bg-hover hover:text-foreground',
        danger: 'border-danger/45 text-danger-ink hover:border-danger hover:bg-danger/12',
      },
      size: {
        default: 'h-11 px-4.5',
        sm: "h-9 rounded-[8px] px-3 text-[13px] [&_svg:not([class*='size-'])]:size-4",
        icon: 'size-11',
        'icon-sm': "size-9 rounded-[8px] [&_svg:not([class*='size-'])]:size-4",
      },
    },
    defaultVariants: {
      variant: 'primary',
      size: 'default',
    },
  },
)

function Button({
  className,
  variant = 'primary',
  size = 'default',
  asChild = false,
  ...props
}: React.ComponentProps<'button'> &
  VariantProps<typeof buttonVariants> & {
    asChild?: boolean
  }) {
  const Comp = asChild ? Slot.Root : 'button'

  return (
    <Comp
      data-slot="button"
      data-variant={variant}
      data-size={size}
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  )
}

export { Button }
