import * as React from 'react'
import { cn } from '@/shared/lib/utils'

// Generated by shadcn (radix-vega), restyled to the canvas `.input` rules.
function Input({ className, type, ...props }: React.ComponentProps<'input'>) {
  return (
    <input
      type={type}
      data-slot="input"
      className={cn(
        'h-11 w-full min-w-0 rounded-sm border border-border bg-surface px-3.5 text-sm text-foreground transition-[border-color,box-shadow,background-color] duration-(--dur-hover) ease-out outline-none placeholder:text-subtle-foreground hover:border-border-strong focus:border-foreground focus:ring-3 focus:ring-foreground/16 aria-invalid:border-danger aria-invalid:focus:ring-danger/24 disabled:cursor-not-allowed disabled:opacity-45',
        className,
      )}
      {...props}
    />
  )
}

export { Input }
