import * as React from 'react'
import { cn } from '@/shared/lib/utils'
import { Label as LabelPrimitive } from 'radix-ui'

// Generated by shadcn (radix-vega), restyled to the canvas `.field-label` rule.
function Label({ className, ...props }: React.ComponentProps<typeof LabelPrimitive.Root>) {
  return (
    <LabelPrimitive.Root
      data-slot="label"
      className={cn(
        'flex items-center gap-2 text-[13px] leading-[18px] font-semibold text-foreground select-none peer-disabled:cursor-not-allowed peer-disabled:opacity-50',
        className,
      )}
      {...props}
    />
  )
}

export { Label }
