import * as React from 'react'
import { cn } from '@/shared/lib/utils'
import { Switch as SwitchPrimitive } from 'radix-ui'

// Generated by shadcn (radix-vega), restyled to the canvas `.toggle` rule (40 x 24 track, 16 px thumb).
function Switch({ className, ...props }: React.ComponentProps<typeof SwitchPrimitive.Root>) {
  return (
    <SwitchPrimitive.Root
      data-slot="switch"
      className={cn(
        'peer inline-flex h-6 w-10 shrink-0 cursor-pointer items-center rounded-full border border-border-strong bg-hover transition-[background-color,border-color] duration-(--dur-hover) ease-out outline-none focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring focus-visible:outline-solid data-checked:border-primary data-checked:bg-primary disabled:cursor-not-allowed disabled:opacity-40',
        className,
      )}
      {...props}
    >
      <SwitchPrimitive.Thumb
        data-slot="switch-thumb"
        className="pointer-events-none block size-4 translate-x-0.75 rounded-full bg-muted-foreground transition-[transform,background-color] duration-(--dur-hover) ease-out data-checked:translate-x-4.75 data-checked:bg-primary-foreground"
      />
    </SwitchPrimitive.Root>
  )
}

export { Switch }
